### ISSUE TITLE
Opening suggested server.host of 127.0.0.1:3001 results in CORS error

### ISSUE THREAD

**Issue by AndreasNasman** [ty-ras/meta#13]
Interacting with the example project on 127.0.0.1:3001 results in a CORS error (localhost works fine):

https://user-images.githubusercontent.com/17124245/236701533-a39a9d55-75dc-4df4-9e38-397864e51a57.mp4

**Comment by AndreasNasman** [comment]
Not sure where to Git blame why `server.host` was changed in `frontend/vite.config.ts` from the default value of `localhost` 🤔

**Comment by AndreasNasman** [comment]
Might be a WSL-only issue 😄

**Comment by stazz** [comment]
I think it's because of the [backend configuration](https://github.com/ty-ras/meta/blob/c38b399ef2a1a0f4065c13f30bcffce327d8e5b7/start/templates/io-ts/be/config-dev.json): 
```json
    "cors": {
      "frontendAddress": "http://localhost:3001"
    }
```

This is why `localhost` is working, and `127.0.0.1` is not.  They are pointing to exactly same thing, but the browser will send different CORS server string for two different addresses.

I also didn't find mentions in template docs talking about navigating to `127.0.0.1` so closing this as not an issue. Please let me know if there is still something that can be done related to this (change to docs, etc). 👍

**Comment by AndreasNasman** [comment]
Ah crap, forgot to mention where the `127.0.0.1` URL came from 😅. When you run `dev` in `frontend` the logged URL is `127.0.0.1`, that's why I ended up using that URL instead of `localhost` 🙂

![image](https://github.com/ty-ras/meta/assets/17124245/743a0a15-9ce3-4abb-ba35-25797506a3dd)
