### ISSUE TITLE
Consider initializing the starter template with Git

### ISSUE THREAD

**Issue by AndreasNasman** [ty-ras/meta#8]
It would be handy if the project was initialized with `git init`, probably quite trivial to add 🙂

**Comment by stazz** [comment]
Hmm true that. I wanted to keep at least the core as minimal as possible, but also no reason not to be helpful. I am thinking something like this:
- Current flow as it is now, followed by
- Post-creation questions (can quit at any time with `q`):
    - Initialize with git?
    - Choose package manager `yarn`/`npm`/`pnpm`/`deno`?. Could emit that `pnpm-workspace.yaml` file at this point if needed. 
    - Install dependencies using selected package manager? y/n

**Comment by stazz** [comment]
This has now been fixed in version `0.13.3`. It turned out to be bigger task than anticipated:
- I extracted the common logic of specifying CLI flags + their associated prompting into [`meow-inquirer`](https://github.com/stazz/meow-inquirer) package.
- Doing so revealed an error with the outputted ESM JS code. This error affected _all_ TyRAS libraries as well, including this and `meow-inquirer` also, so it had to be fixed.
- The fix for the error involved creating [`eslint-plugin-path-import-extension`](https://github.com/stazz/eslint-plugin-path-import-extension), which was my first time ever creating ESLint plugin.

Then, of course, the actual code of Git initializing (and dependency installation!) needed to be written, but that turned out to be a breeze with `meow-inquirer`.
